name: CzmTestKit
channels:
  - conda-forge
  - defaults
  - bioconda
dependencies:
  - python=3.9.1
  - python-dateutil=2.8.2
  - python_abi=3.9
  - ffmpeg-python=0.2.0
  - ipykernel=6.7.0
  - ipython=8.0.1
  - jupyter_client=7.1.2
  - jupyter_core=4.9.1
  - mpmath=1.2.1
  - matplotlib=3.5.1
  - matplotlib-inline=0.1.3
  - numpy=1.22.1
  - pandas=1.4.0
  - pip=20.3.1
  - scipy=1.7.3
  - setuptools=51.0.0
  - twine=3.8.0
  - ffmpeg